### ISSUE TITLE
Exception happened during processing of request from

### ISSUE THREAD

**Issue by bonald** [Bestoa/Claymore-NoFee-Proxy#1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "claymore-nofee-proxy.py", line 78, in handle
    self.handle_tcp(sock, remote)
  File "claymore-nofee-proxy.py", line 63, in handle_tcp
    if remote.send(remove_devfee(r_data)) <= 0:
  File "claymore-nofee-proxy.py", line 52, in remove_devfee
    return str.encode(data)
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'

**Comment by Bestoa** [comment]
Please use Python 3.x.
